package edu.cmu.lti.deiis.hw5.answer_selection;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;

import org.apache.uima.UimaContext;
import org.apache.uima.analysis_component.JCasAnnotator_ImplBase;
import org.apache.uima.analysis_engine.AnalysisEngineProcessException;
import org.apache.uima.jcas.JCas;
import org.apache.uima.jcas.cas.DoubleArray;
import org.apache.uima.resource.ResourceInitializationException;

import edu.cmu.lti.qalab.types.Answer;
import edu.cmu.lti.qalab.types.CandidateAnswer;
import edu.cmu.lti.qalab.types.CandidateSentence;
import edu.cmu.lti.qalab.types.Question;
import edu.cmu.lti.qalab.types.QuestionAnswerSet;
import edu.cmu.lti.qalab.types.TestDocument;
import edu.cmu.lti.qalab.utils.Utils;

public class AnswerSelectionByLinearInterp extends JCasAnnotator_ImplBase {
  float SCORE_THR = (float) 0.1;
  
  @Override
  public void initialize(UimaContext context) throws ResourceInitializationException {
    super.initialize(context);
    SCORE_THR = (Float) context.getConfigParameterValue("SCORE_THR");
  }

  @Override
  public void process(JCas aJCas) throws AnalysisEngineProcessException {
    TestDocument testDoc = Utils.getTestDocumentFromCAS(aJCas);
    ArrayList<QuestionAnswerSet> qaSet = Utils.fromFSListToCollection(testDoc.getQaList(),
            QuestionAnswerSet.class);
    int matched = 0;
    int total = 0;
    int unanswered = 0;
    for (int i = 0; i < qaSet.size(); i++) {
      System.out.println("Processing Question No." + (i+1));
      Question question = qaSet.get(i).getQuestion();
      System.out.println("Question: " + question.getText());
      System.out.println("Candidate Answer" + "\t" + "finalScore");
      ArrayList<Answer> choiceList = Utils.fromFSListToCollection(qaSet.get(i).getAnswerList(),
              Answer.class);
      
      for (int j = 0; j < choiceList.size(); j++) {
        Answer candAnswer = choiceList.get(j);
        DoubleArray baselineScore = candAnswer.getBaselineScore();
        double PMIScore = candAnswer.getPMIscore();
        double finalScore = getFinalScore(baselineScore, PMIScore);
        candAnswer.setFinalScore(finalScore);
      }
      
      Collections.sort(choiceList, new AnswerFinalScoreComparator());
      Answer topAnswer = choiceList.get(0);
      if (topAnswer.getIsCorrect()){
        matched++;
      }
      
      //XXX unanswered and matched at same time?
      if (topAnswer.getFinalScore() < SCORE_THR) {
        unanswered++;
      }
      
      for (Answer candAns : choiceList) {
        System.out.println(candAns.getText() + "\t" + candAns.getFinalScore() + "\t"
                + (candAns.getIsCorrect() ? "(gold standard)" : ""));
      }

      total++;
      System.out.println("================================================");
    }

    System.out.println("Correct: " + matched + "/" + total + "=" + ((matched * 100.0) / total)
            + "%");
    // TO DO: Reader of this pipe line should read from xmi generated by
    // SimpleRunCPE
    double cAt1 = (((double) matched) / ((double) total) * unanswered + (double) matched)
            * (1.0 / total);
    System.out.println("c@1 score:" + cAt1);

  }

  private double getFinalScore(DoubleArray baselineScore, double PMIScore) {
    double result = 0;

    if (baselineScore.size() < 6){
      System.err.println("ERROR: 6 > baselineScore.size() = " + baselineScore.size());
      return PMIScore;
    }
    
    result += baselineScore.get(0) * 0.2 + baselineScore.get(1) * 0.1 + baselineScore.get(2) * 0.1
            + baselineScore.get(3) * 0.1 + baselineScore.get(4) * 0.1 + baselineScore.get(5) * 0.1
            + PMIScore * 0.3;
    
    return result;
  }

}
